"""AGENTS.md formatter.

AGENTS.md is the emerging cross-tool standard for AI agent instructions,
supported by Claude Code, OpenAI Codex, Gemini CLI, Cursor, and others.
Generated by saar -- https://getsaar.com

Content is identical to CLAUDE.md but uses generic agent framing rather
than Claude-specific language. This makes it the better default: any AI
tool can consume it, and tool-specific files (CLAUDE.md, .cursorrules) can
be generated alongside it via --format all.
"""
from saar.models import CodebaseDNA
from saar.formatters._tribal import render_tribal_knowledge


def render_agents_md(dna: CodebaseDNA) -> str:
    """Render DNA as an AGENTS.md file."""
    lines = [f"# AGENTS.md -- {dna.repo_name}\n"]
    lines.append(
        "Generated by [saar](https://getsaar.com). "
        "Re-run `saar . --format agents` to update auto-detected sections.\n"
    )

    if dna.detected_framework:
        lines.append(f"This is a **{dna.detected_framework}** project.\n")

    # -- codebase stats (orientation for the agent) --
    if dna.total_functions or dna.total_classes:
        parts = []
        if dna.total_functions:
            parts.append(f"{dna.total_functions:,} functions")
        if dna.total_classes:
            parts.append(f"{dna.total_classes:,} classes")
        if dna.async_adoption_pct > 0:
            parts.append(f"{dna.async_adoption_pct:.0f}% async")
        if dna.type_hint_pct > 0:
            parts.append(f"{dna.type_hint_pct:.0f}% type-hinted")
        lines.append(", ".join(parts) + ".\n")

    # -- language distribution --
    if dna.language_distribution:
        lang_str = ", ".join(
            f"{lang} ({count} files)"
            for lang, count in sorted(
                dna.language_distribution.items(), key=lambda x: -x[1]
            )
        )
        lines.append(f"**Languages:** {lang_str}\n")

    # -- coding conventions --
    lines.append("## Coding Conventions\n")
    nc = dna.naming_conventions
    if nc.function_style != "unknown":
        lines.append(f"- Functions: `{nc.function_style}`")
    if nc.class_style != "unknown":
        lines.append(f"- Classes: `{nc.class_style}`")
    if nc.constant_style != "unknown":
        lines.append(f"- Constants: `{nc.constant_style}`")
    if nc.file_style != "unknown":
        lines.append(f"- Files: `{nc.file_style}`")

    if dna.common_imports:
        lines.append("\nPreferred imports:")
        lines.append("```")
        for imp in dna.common_imports[:10]:
            lines.append(imp)
        lines.append("```")

    # -- logging --
    lp = dna.logging_patterns
    if lp.logger_import or lp.structured_logging:
        lines.append("\n## Logging\n")
        if lp.logger_import:
            lines.append(f"- Use `{lp.logger_import}` -- never bare `print()`")
        if lp.structured_logging:
            lines.append("- Structured logging (JSON format)")

    # -- critical files --
    if dna.critical_files:
        lines.append("\n## Critical Files\n")
        lines.append(
            "These files have the most dependents in the codebase. "
            "Understand them before making changes.\n"
        )
        for cf in dna.critical_files[:8]:
            f = cf.get("file", "") if isinstance(cf, dict) else cf
            d = cf.get("dependents", 0) if isinstance(cf, dict) else 0
            if f:
                dep_note = f" ({d} dependents)" if d else ""
                lines.append(f"- `{f}`{dep_note}")

    # -- architecture --
    sp = dna.service_patterns
    ap = dna.auth_patterns
    if sp.singleton_services or sp.dependencies_file or ap.middleware_used or ap.auth_decorators:
        lines.append("\n## Architecture\n")
        if sp.singleton_services:
            lines.append(f"- Services are singletons: `{', '.join(sp.singleton_services)}`")
        if sp.dependencies_file:
            lines.append(f"- Dependency wiring: `{sp.dependencies_file}`")
        if sp.injection_pattern:
            lines.append(f"- DI pattern: {sp.injection_pattern}")
        if ap.middleware_used:
            lines.append(f"- Auth middleware: `{', '.join(ap.middleware_used)}`")
        if ap.auth_decorators:
            lines.append(f"- Auth decorators: `{', '.join(ap.auth_decorators)}`")
        if ap.auth_context_type:
            lines.append(f"- Auth context: `{ap.auth_context_type}`")

    # -- database --
    db = dna.database_patterns
    if db.orm_used:
        lines.append("\n## Database\n")
        lines.append(f"- ORM: {db.orm_used}")
        if db.id_type != "unknown":
            lines.append(f"- ID type: `{db.id_type}`")
        if db.timestamp_type != "unknown":
            lines.append(f"- Timestamp type: `{db.timestamp_type}`")
        if db.has_rls:
            lines.append("- Row Level Security enabled -- always respect RLS policies")
        if db.cascade_deletes:
            lines.append("- Cascade deletes on parent-child relationships")

    # -- error handling --
    ep = dna.error_patterns
    if ep.exception_classes or ep.http_exception_usage or ep.logging_on_error:
        lines.append("\n## Error Handling\n")
        if ep.exception_classes:
            lines.append(f"- Use domain exceptions: `{', '.join(ep.exception_classes)}`")
        if ep.http_exception_usage:
            lines.append("- Use HTTPException for API errors")
        if ep.logging_on_error:
            lines.append("- Log exceptions before re-raising")

    # -- testing --
    tp = dna.test_patterns
    if tp.framework:
        lines.append("\n## Testing\n")
        lines.append(f"- Framework: {tp.framework}")
        lines.append(f"- Pattern: `{tp.test_file_pattern}`")
        if tp.fixture_style:
            lines.append(f"- Fixtures: {tp.fixture_style}")
        if tp.mock_library:
            lines.append(f"- Mocking: {tp.mock_library}")
        if tp.has_conftest:
            lines.append("- Shared fixtures in `conftest.py`")

    # -- API --
    if dna.api_versioning or dna.router_pattern:
        lines.append("\n## API\n")
        if dna.api_versioning:
            lines.append(f"- Versioning: `{dna.api_versioning}`")
        if dna.router_pattern:
            lines.append(f"- Router pattern: `{dna.router_pattern}`")

    # -- circular dep warnings --
    if dna.circular_dependencies:
        lines.append("\n## Circular Dependencies (resolve before adding more)\n")
        for pair in dna.circular_dependencies[:5]:
            lines.append(f"- `{pair[0]}` <-> `{pair[1]}`")

    # -- tribal knowledge from guided interview (highest value content) --
    tribal = render_tribal_knowledge(dna.interview)
    if tribal:
        lines.append(tribal)

    # -- team rules verbatim --
    if dna.team_rules:
        lines.append("\n## Project-Specific Rules\n")
        if dna.team_rules_source:
            lines.append(f"*From `{dna.team_rules_source}`*\n")
        lines.append(dna.team_rules)

    return "\n".join(lines) + "\n"
